[watch]
paths = ["."]
include = ["**/*.c", "**/*.h", "ember.toml", "ember.clang.toml", "ember.gcc.toml"]
ignore = [".git/**", ".ember/**"]
debounce_ms = 150
poll = false

[build]
cmd = "cl /nologo /W4 /Fe{out} main.c"
stops_running = false

[run]
cmd = "{out}"
cwd = "."
kill_timeout_ms = 2000

[ui]
color = true
